### ISSUE TITLE
Ask about Ablation Study

### ISSUE THREAD

**Issue by ghost** [mengtong0110/InferDPT#2]
Hello, your work is very innovative, but I have two questions:

1. I directly used the code you provided to perturb the example sentence in your paper(Fig. 1) and constructed the large model input using the prompts you provided. However, the perturbed generation are almost entirely unrelated to the raw document. I used a privacy budget of eps = 6.0 and also tried changing its value, but it still doesn't work. Am I using it incorrectly, or do I need to make some other configurations?

2. My second question is, how can we ensure that the final high-quality extracted generation are a refinement (or alignment) of the local small model with the perturbed generation of the remote large model, rather than the small model generating them based on the raw private document? After all, the small model has access to the complete original input.

**Comment by mengtong0110** [comment]
For the first question, your observation is correct: the perturbed response changes the semantics of the generated sentence, and this indeed protects the original generation (as the perturbed generation will share the same tokens with the original generation). InferDPT samples tokens from the perturbed generation (in the extraction module) for its generation of the original document and obtained an aligned generation.

**Comment by mengtong0110** [comment]
For the second question, I believe there are other approaches besides the ones mentioned in our paper.  Indeed, the architecture of InferDPT is 
quite similar to RAG.  You might find some methods in this area for reference to obtain better quality : )
